import { Poppins } from 'next/font/google';
import type { Metadata } from "next";
import "./globals.css";
import Navbar from '@/components/shared/Navbar/Navbar';
import StorageProvider from '@/providers/StorageProvider';
import SmoothScrolling from '@/providers/SmoothScrolling';

export const metadata: Metadata = {
  title: "Wool",
  description: "Generated by create next app"
};

const poppins = Poppins({
  weight: ['400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <StorageProvider>
        <SmoothScrolling>
        <body className="body-style">
          <Navbar />
          {children}
        </body>
        </SmoothScrolling>
      </StorageProvider>
    </html>
  );
}