import { Poppins } from 'next/font/google';
import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import Navbar from '@/components/shared/Navbar/Navbar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const poppins = Poppins({
  weight: ['400', '500', '600', '700', '800', '900'], // Valid weights for Poppins
  subsets: ['latin'], // Valid subset
  display: 'swap', // Optimize font loading
});

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <Navbar/>
        <body className={`body-style ${poppins.className}`}>
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
